#!/usr/local/bin/bash


function chek_logos(){

          LOGO_NB=0
          LOGOS_PRESET[0]=""
          LOGOS_PRESET[1]=""

          for LOGO_ADD in $(echo $LOGOS_ADD)
          do

                LOGO_PRESET=$(grep  "^LOGO_NAME=$LOGO_ADD${PLAY_SIZE} .*" ${APP_DIR}/config/LOGOS)



                if [[ ! -z $LOGO_PRESET ]]
                then

                    LOGOS_PRESET[$LOGO_NB]=$LOGO_PRESET

                    
                    LOGO_NB=$[$LOGO_NB+1]
                fi

          [[ $LOGO_NB -eq 2 ]] && break

          done

}


function add_logo(){
		VF_MOVIE=""


        chek_logos


        ### get the number of logos


        [[ $DEBUG -gt 0 ]] && echo "number of valide logos  $LOGO_NB"



                ### 1 logo ###




                if [[ $LOGO_NB -eq 1 ]]
                then



                                ### eval the preset values

                                echo "${LOGOS_PRESET[0]}"
                                eval "${LOGOS_PRESET[0]}"
                                VF_MOVIE=" [in]; movie=$APP_DIR/logos/${LOGO_FILE},scale=${LOGO_W}:${LOGO_H} [logo];[in][logo] overlay=${LOGO_X}:${LOGO_Y} [out] "
                                [[ $DEBUG -gt 0 ]] && echo "$VF_MOVIE"










                ### 2 logos ###



                elif [[ $LOGO_NB -eq 2 ]]
                then


                        VF_MOVIE_1=""
                        VF_MOVIE_2=""
                        VF_MOVIE_3=""
                        VF_MOVIE_4=""


                        ### eval the preset values

                        eval "${LOGOS_PRESET[0]}"

                        VF_MOVIE_1="[in];movie=$APP_DIR/logos/${LOGO_FILE} , scale=${LOGO_W}:${LOGO_H} [logo1];"
                        VF_MOVIE_3=" [in][logo1] overlay=${LOGO_X}:${LOGO_Y} [in+logo1]; "


                        ### eval the preset values

                        eval "${LOGOS_PRESET[1]}"

                        VF_MOVIE_2=" movie=$APP_DIR/logos/${LOGO_FILE} , scale=${LOGO_W}:${LOGO_H} [logo2];"
                        VF_MOVIE_4=" [in+logo1][logo2] overlay=${LOGO_X}:${LOGO_Y} [out] "




                    VF_MOVIE="$VF_MOVIE_1 $VF_MOVIE_2 $VF_MOVIE_3 $VF_MOVIE_4"
                    [[ $DEBUG -gt 0 ]] && echo "$VF_MOVIE"




                fi
           
}
 