#!/usr/local/bin/bash


#########################
function dump_audio(){
#########################

		if [[ $OVERWRITE == 0 && -f "${DIRECTORY}/$SUBDIR/audio.wav" ]]
		then

        echo -e "${yellow}# Create audio.wav ${NC}"
        echo -e "${green}# This file (audio.wav) already exit.We going to use it${NC}"

		else

        echo -e "${yellow}# create audio.wav ${NC}"
        COMMAND="${MPLAYER_LATEST} -ao pcm:fast:waveheader:file=${DIRECTORY}/$SUBDIR/audio.wav -vc dummy -vo null ${INPUT}"
        [[ $DEBUG -gt 1 ]] && QUEIT=""  || QUEIT=" > /dev/null  2>&1"
        eval "$COMMAND $QUEIT" && echo -e ${green}$COMMAND$QUEIT${NC} ||  echo -e ${red}$COMMAND${NC}



		fi

}

#########################
function resample_audio(){
#########################

      BITS=`file ${DIRECTORY}/${SUBDIR}/audio.wav| grep -oE "PCM, 8 bit|PCM, 24 bit"|grep -oE "8|24"`

			if [[ ! -z  $BITS ]];
			then

          echo -e "${yellow}# Resampling PCM 8 bit to PCM 16 bit${NC}"

          COMMAND="sox -b $BITS ${DIRECTORY}/${SUBDIR}/audio.wav -r 48000 -s ${DIRECTORY}/${SUBDIR}/resample.wav && cp ${DIRECTORY}/${SUBDIR}/resample.wav ${DIRECTORY}/${SUBDIR}/audio.wav "
          [[ $DEBUG -gt 1 ]] && QUEIT=""  || QUEIT="  2>/dev/null"
          eval "$COMMAND $QUEIT" && echo -e ${green}$COMMAND$QUEIT${NC} ||  echo -e ${red}$COMMAND${NC}

			else

          echo -e "${yellow}# No audio resampling needed ${NC}"

			fi
}