#!/usr/local/bin/bash




X264_VERSION="0.65"
MPLAYER_VERSION=
IMAGEMAGICK_VERSION="6.5.1"

# config
INSTALL=0
REINSTALL=0


usage() {
echo >&2 "Usage: `basename $0` [-i install] [-i reinstall]"
}


    while getopts "iI" option
    do
	case "$option" in
	  i)	INSTALL=1;;
	  I)	REINSTALL=1;;
	[?])    usage
		exit 1;;
	esac
    done
    shift $(($OPTIND - 1))


### Define some colors: ###

red='\e[0;31m'
RED='\e[1;31m'

green='\e[0;32m'
GREEN='\e[1;32m'

yellow='\e[0;33m'
YELLOW='\e[1;33m'

NC='\e[0m'

      ### get System ###

  	  echo -e "$GREEN System: $(uname) $NC"

      ### get the Distribution version, codename  ###


  	  echo -e "$GREEN Distribution: $(lsb_release -si) $NC"
  	  echo -e "$GREEN Version: $(lsb_release -sr) $NC"
  	  echo -e "$GREEN codename: $(lsb_release -sc) $NC"




		. lib/check/check_cpu.sh


  ### check mplayer ###

	echo -en "mplayer\t"

	if [[  $(dpkg -s mplayer| grep Version:.*| grep -o 33269) ]]
	then
	echo -e "${green} 33269 ${NC}"

  elif [[  $(dpkg -s mplayer| grep Version:.*) ]]
  then

	echo -e "${yellow}$(dpkg -s mplayer| grep Version:.*)${NC}"

	else

	echo -e "${RED}Not installed!{NC}"

	fi





  ### check ffmpip (17655/0.65) ###

	echo -en "ffmpip (17655/0.65)\t"

	if [[  $(dpkg -s ffmpip| grep Version:.*) ]]
	then

    echo -e "${GREEN} installed ${NC}"
    echo -e "${YELLOW} more info about ffmpeg ${NC}"
    echo -e "${green}$(/opt/pip/bin/ffmpeg -version 2>/dev/null)${NC}"
    echo -e "${YELLOW} more info about x264 ${NC}"
    echo -e "${green}$(/opt/pip/bin/x264 --version)${NC}"


	else

    echo -e "${RED}Not installed!{NC}"

	fi

  ### check ffmpeg-webm ###

	echo -en "ffmpeg-webm \t"

	if [[  $(dpkg -s ffmpeg-webm| grep Version:.*) ]]
	then

    echo -e "${GREEN} installed ${NC}"
    echo -e "${YELLOW} more info about ffmpeg ${NC}"
    echo -e "${green}$(/opt/webm/bin/ffmpeg -version 2>/dev/null)${NC}"
    echo -e "${YELLOW} more info about x264 ${NC}"
    echo -e "${green}$(/opt/webm/bin/x264 --version)${NC}"


	else

    echo -e "${RED}Not installed!{NC}"

	fi



  ### check mediainfo 7.8 ###

	echo -en "mediainfo (7.8)\t"

	if [[  $(dpkg -s mediainfo| grep Version:.*| grep -o 7.8) ]]
	then
	echo -e "${green} 7.8 ${NC}"

  elif [[  $(dpkg -s mediainfo| grep Version:.*) ]]
  then

	echo -e "${yellow}$(dpkg -s mediainfo| grep Version:.*)${NC}"

	else

	echo -e "${RED}Not installed!{NC}"

	fi